xcodeproj 'Amalon iOS Example'
workspace '../Amalon'
inhibit_all_warnings!

def import_pods
  pod 'Amalon', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'Amalon iOS Example'
  import_pods
end